import { Radio as RadioGroupOption } from "@headlessui/react"
import { Text, clx } from "@modules/common/components/ui"
import React, { useContext, useMemo, useState, type JSX } from "react"

import Radio from "@modules/common/components/radio"

import { isManual } from "@lib/constants"
import SkeletonCardDetails from "@modules/skeletons/components/skeleton-card-details"
import { CardElement } from "@stripe/react-stripe-js"
import { StripeCardElementOptions } from "@stripe/stripe-js"
import PaymentTest from "../payment-test"
import { StripeContext } from "../payment-wrapper/stripe-wrapper"

type PaymentContainerProps = {
  paymentProviderId: string
  selectedPaymentOptionId: string | null
  disabled?: boolean
  paymentInfoMap: Record<string, { title: string; icon: JSX.Element }>
  children?: React.ReactNode
}

const PaymentContainer: React.FC<PaymentContainerProps> = ({
  paymentProviderId,
  selectedPaymentOptionId,
  paymentInfoMap,
  disabled = false,
  children,
}) => {
  const isDevelopment = process.env.NODE_ENV === "development"
  
  const [transferMethod, setTransferMethod] = useState<"fps" | "payme">("fps")
  const [receiptFile, setReceiptFile] = useState<File | null>(null)
  
  // NEW: Keep track of loading state!
  const [isUploading, setIsUploading] = useState(false)

  // UPDATED: Added the new long ID generated by your database rebuild
  const isCustomManualPayment = 
    paymentProviderId === "pp_fps-manual_fps-manual" || 
    paymentProviderId === "pp_system_default" || 
    paymentProviderId === "fps-manual";
    
  const isCustomManualSelected = 
    selectedPaymentOptionId === "pp_fps-manual_fps-manual" || 
    selectedPaymentOptionId === "pp_system_default" || 
    selectedPaymentOptionId === "fps-manual";

  // NEW: The upload handler function
  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      const file = e.target.files[0];
      setIsUploading(true);

      const formData = new FormData();
      formData.append("receipt", file);
      formData.append("method", transferMethod.toUpperCase()); // "FPS" or "PAYME"

      try {
        const res = await fetch("/api/upload-receipt", {
          method: "POST",
          body: formData,
        });

        if (res.ok) {
          setReceiptFile(file); // Show the green success box!
        } else {
          alert("Upload failed. Please try again.");
        }
      } catch (error) {
        console.error(error);
        alert("An error occurred during upload.");
      } finally {
        setIsUploading(false);
      }
    }
  };

  return (
    <RadioGroupOption
      key={paymentProviderId}
      value={paymentProviderId}
      disabled={disabled}
      className={clx(
        "flex flex-col gap-y-2 text-small-regular cursor-pointer py-4 border rounded-rounded px-8 mb-2 hover:shadow-borders-interactive-with-active",
        {
          "border-ui-border-interactive":
            selectedPaymentOptionId === paymentProviderId,
        }
      )}
    >
      <div className="flex items-center justify-between ">
        <div className="flex items-center gap-x-4">
          <Radio checked={selectedPaymentOptionId === paymentProviderId} />
          <Text className="text-base-regular">
            {isCustomManualPayment ? "Manual Bank Transfer (FPS / PayMe)" : paymentInfoMap[paymentProviderId]?.title || paymentProviderId}
          </Text>
          {isManual(paymentProviderId) && isDevelopment && !isCustomManualPayment && (
            <PaymentTest className="hidden small:block" />
          )}
        </div>
        <span className="justify-self-end text-ui-fg-base">
          {paymentInfoMap[paymentProviderId]?.icon}
        </span>
      </div>

      {isCustomManualPayment && isCustomManualSelected && (
        <div className="flex flex-col p-6 mt-4 bg-ui-bg-subtle rounded-lg border border-ui-border-base transition-all duration-300 ease-in-out cursor-default" onClick={(e) => e.stopPropagation()}>
          
          <div className="flex gap-4 mb-6 justify-center w-full">
            <button
              type="button"
              onClick={() => setTransferMethod("fps")}
              className={`flex-1 py-3 rounded-md border font-semibold transition-colors ${
                transferMethod === "fps" 
                ? "bg-[#005e54] text-white border-[#005e54]" 
                : "bg-white text-gray-700 border-gray-300 hover:bg-gray-50"
              }`}
            >
              FPS 轉數快
            </button>
            <button
              type="button"
              onClick={() => setTransferMethod("payme")}
              className={`flex-1 py-3 rounded-md border font-semibold transition-colors ${
                transferMethod === "payme" 
                ? "bg-[#e52144] text-white border-[#e52144]" 
                : "bg-white text-gray-700 border-gray-300 hover:bg-gray-50"
              }`}
            >
              PayMe
            </button>
          </div>

          <div className="flex flex-col items-center mb-6">
            <img 
              src={transferMethod === "fps" ? "/fps-qr.png" : "/payme-qr.png"} 
              alt={`${transferMethod} QR Code`} 
              className="w-48 h-48 border-2 border-ui-border-base rounded-md shadow-sm mb-2" 
            />
            <Text className="text-small-regular text-center text-ui-fg-subtle mt-2">
              Please transfer the exact order amount using the {transferMethod === "fps" ? "FPS" : "PayMe"} QR code above.
            </Text>
          </div>

          <div className="w-full border-t border-ui-border-base pt-6">
            <label className="block text-base-regular font-semibold mb-2 text-ui-fg-base">
              Upload Transfer Receipt
            </label>
            <p className="text-small-regular text-ui-fg-subtle mb-4">
              Please upload a screenshot of your successful transaction (.jpg, .png, .pdf) to verify your order.
            </p>
            
            <input 
              type="file" 
              accept=".jpg,.jpeg,.png,.pdf"
              onChange={handleFileUpload}
              disabled={isUploading}
              className={`block w-full text-sm text-gray-500
                file:mr-4 file:py-2 file:px-4
                file:rounded-md file:border-0
                file:text-sm file:font-semibold
                file:bg-ui-bg-field file:text-ui-fg-base
                hover:file:bg-ui-bg-field-hover border border-ui-border-base rounded-md p-2 bg-white ${isUploading ? "opacity-50 cursor-not-allowed" : ""}`}
            />

            {/* Loading Indicator */}
            {isUploading && (
              <div className="mt-3 text-sm text-blue-600 font-medium animate-pulse">
                ⏳ Uploading receipt securely...
              </div>
            )}

            {/* Success Box */}
            {receiptFile && !isUploading && (
              <div className="mt-3 p-3 bg-green-50 border border-green-200 rounded-md flex items-center gap-2">
                <span className="text-green-600">✅</span>
                <span className="text-sm font-medium text-green-800">
                  Attached: {receiptFile.name}
                </span>
              </div>
            )}
          </div>
        </div>
      )}

      {children}
    </RadioGroupOption>
  )
}

export default PaymentContainer

export const StripeCardContainer = ({
  paymentProviderId,
  selectedPaymentOptionId,
  paymentInfoMap,
  disabled = false,
  setCardBrand,
  setError,
  setCardComplete,
}: Omit<PaymentContainerProps, "children"> & {
  setCardBrand: (brand: string) => void
  setError: (error: string | null) => void
  setCardComplete: (complete: boolean) => void
}) => {
  const stripeReady = useContext(StripeContext)

  const useOptions: StripeCardElementOptions = useMemo(() => {
    return {
      style: {
        base: {
          fontFamily: "Inter, sans-serif",
          color: "#424270",
          "::placeholder": {
            color: "rgb(107 114 128)",
          },
        },
      },
      classes: {
        base: "pt-3 pb-1 block w-full h-11 px-4 mt-0 bg-ui-bg-field border rounded-md appearance-none focus:outline-none focus:ring-0 focus:shadow-borders-interactive-with-active border-ui-border-base hover:bg-ui-bg-field-hover transition-all duration-300 ease-in-out",
      },
    }
  }, [])

  return (
    <PaymentContainer
      paymentProviderId={paymentProviderId}
      selectedPaymentOptionId={selectedPaymentOptionId}
      paymentInfoMap={paymentInfoMap}
      disabled={disabled}
    >
      {selectedPaymentOptionId === paymentProviderId &&
        (stripeReady ? (
          <div className="my-4 transition-all duration-150 ease-in-out">
            <Text className="txt-medium-plus text-ui-fg-base mb-1">
              Enter your card details:
            </Text>
            <CardElement
              options={useOptions as StripeCardElementOptions}
              onChange={(e) => {
                setCardBrand(
                  e.brand && e.brand.charAt(0).toUpperCase() + e.brand.slice(1)
                )
                setError(e.error?.message || null)
                setCardComplete(e.complete)
              }}
            />
          </div>
        ) : (
          <SkeletonCardDetails />
        ))}
    </PaymentContainer>
  )
}